{% set version = "0.8.0" %}

package:
    name: wradlib
    version: {{ version }}

source:
    fn: wradlib-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
    md5: 3ed24ca856a707757148a9ee298feb0c

build:
    number: 0
    #skip: True # [py35 and win]
   
requirements:
    build:
        - python
        - numpy 
        - scipy 
        - matplotlib 
        - h5py 
        - netcdf4 
        - gdal
        # The gdal package on OS X is missing a dependency on krb5
        - krb5  # [osx]
    run:
        - python
        - numpy 
        - scipy 
        - matplotlib 
        - h5py 
        - netcdf4 
        - gdal
        - krb5  # [osx]

test:
    imports:
        - wradlib

about:
    home: http://wradlib.org/
    license: MIT
    summary: "Open Source Library for Weather Radar Data Processing"

extra:
    recipe-maintainers:
        - jjhelmus
        - kmuehlbauer
