travis:
  secure:
    BINSTAR_TOKEN: bWeJIP7nDTY2+rVGAvs7BrCXXGbXN3pCCAywf/1SYPjGdSQ+tit0bPNb0MP5mFjyvj0N1AzR/MHzVOg1rbFr06/38wF+C6g35HzE3KGbAQPmA5pHamdNi1UpQtYDE6if217I1trb5LRXwNOq1zLDhMJh1IiAE2G+B8J2S0CwfkSQH6hAAObcsGhgSkLeLx2Xwt9WlqUc3OMKPSUkMjBmRJM2jKBmOSkEQbVPkVphUg1JJ7zdgi2oNk6rDJqrOA2q2tjicG4QSfk2cFCNUqu8GTBdU2VPx286Ia6vjLiUMkOu71aAp+7n3e9x+tjPixr1ey9FakA55GG5mbr7X84GcZCRhdgDVGR3ZOY+sbjX6KYXWOI8DvR5KAbSrEV33Kq3EyZ3sVrPd8L3cbAOgo+5RAsFCSqHpCQJ5pd5Ls7Zrm2g9mFsY18G7lEjXBxiz7cP44Uwn1asSaumBGzbPbNfo/AnW8ouF6chrqBAK5eMZ3r1raZJxvy19s+W7gRr05OS2RyUlbnTAfsAWV6weu+Clf1DUKgHJm7uXc2ucPXw4bMItT+AN3dntk5RIFo9Giix7QrvaC46/HLesYWCSOtctmMaNHdo+sDTzLtqKALKCOMgQz6+L/VajmpprLB07UMGuy7WeDC0ngK1xZiKEqIIGrDQP7NGdYfjgYbAACyKGQw=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
